# Generated by Django 6.1.1 on 2026-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='queued_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
